Repository spiral/docs, pull requests merged in 2023-03, with the labels that each got.

#519 Hotfix/seeder
  docs/en/testing/database.md
Labels: bug

#520 Adds Realtime chat to the cookbook section
  docs/en/cookbook/simple-chat.md
  docs/en/manifest.json
Labels: enhancement, section: COOKBOOK

#521 Adds information about console command attributes
  docs/en/console/commands.md
Labels: enhancement, section: CONSOLE

#522 Adds information about repeatable filters definition
  docs/en/filters/filter.md
Labels: enhancement

#523 Adds information about custom mail transports
  docs/en/advanced/sendit.md
Labels: enhancement, section: SendIt

#524 Adds Centrifugo API page
  docs/en/manifest.json
  docs/en/websockets/api.md
Labels: enhancement, section: Event Broadcasting

#525 Centrifugo RPC auth with AuthContext
  docs/en/websockets/interceptors.md
Labels: enhancement

#526 Adds information about fileserver plugin for the storage component
  docs/en/advanced/storage.md
Labels: enhancement, section: Storage

#528 Adds information about using nginx proxy for centrifugo server
  docs/en/websockets/configuration.md
Labels: enhancement

#529 Docs typo fixed
  docs/en/basics/orm.md
Labels: bug
