Repository spiral/docs, pull requests merged in 2023-01, with the labels that each got.

#432 Adds information about broadcasting and an example of authorization o…
  docs/en/manifest.json
  docs/en/readme.md
  docs/en/websockets/broadcasting.md
  docs/en/websockets/services.md
Labels: section: Event Broadcasting

#436 Adds information about kernel dispatchers and updates custom dispatch…
  docs/en/cookbook/custom-dispatcher.md
  docs/en/framework/dispatcher.md
  docs/en/manifest.json
  docs/en/readme.md
Labels: enhancement, section: FRAMEWORK, section: COOKBOOK

#431 Update commands docs
  docs/en/start/commands.md
Labels: enhancement

#434 Update contribution guide
  docs/en/about/contributing.md
Labels: enhancement

#439 Create a schema for auth
  docs/en/security/authentication.md
Labels: enhancement

#438 Update versioning
  docs/en/about/semver.md
Labels: enhancement

#440 Updates information about validation component
  docs/en/component/attributes.md
  docs/en/component/cache.md
  docs/en/component/data-grid.md
  docs/en/component/distribution.md
  docs/en/component/sendit.md
  docs/en/component/serializer.md
  docs/en/component/storage.md
  docs/en/component/telemetry.md
  docs/en/component/tokenizer.md
  docs/en/database/configuration.md
  docs/en/debug/exceptions.md
  docs/en/extension/sentry.md
  docs/en/filters/bridge.md
  docs/en/filters/composite.md
  docs/en/filters/configuration.md
  docs/en/filters/filter.md
  docs/en/framework/bootloaders.md
  docs/en/grpc/configuration.md
  docs/en/http/annotated-routes.md
  docs/en/http/configuration.md
  docs/en/http/errors.md
  docs/en/i18n/views.md
  docs/en/manifest.json
  docs/en/queue/roadrunner.md
  docs/en/readme.md
  docs/en/validation/factory.md
  docs/en/validation/laravel.md
  docs/en/validation/spiral.md
  docs/en/validation/symfony.md
  docs/en/views/twig.md
Labels: section: VALIDATION, section: REQUEST VALIDATION

#442 Add interceptors for filters
  docs/en/filters/interceptors.md
  docs/en/manifest.json
  docs/en/readme.md
Labels: section: REQUEST VALIDATION

#413 Remove `ValidationInterceptor` from "Domain Core"
  docs/en/basics/quick-start.md
Labels: section: GETTING STARTED

#443 Updates console commands
  docs/en/console/commands.md
  docs/en/console/configuration.md
  docs/en/console/sequences.md
  docs/en/manifest.json
  docs/en/readme.md
Labels: enhancement, section: CONSOLE

#444 Updates information about tokenizer
  docs/en/component/tokenizer.md
Labels: enhancement

#392 Added information about session cache handler
  docs/en/http/session.md
Labels: section: HTTP

#420 Added example of anonymous bootloader registration
  docs/en/framework/bootloaders.md
  docs/en/framework/kernel.md
Labels: enhancement, section: HTTP

#391 Added information about exception verbosity
  docs/en/component/exceptions.md
Labels: section: Exceptions

#445 Updates metrics component
  docs/en/component/metrics.md
Labels: enhancement

#454 Updates Application Lifecycle
  docs/en/start/workers.md
Labels: enhancement, section: FRAMEWORK

#456 Adds tutorial for user authentication based on JWT tokens
  docs/en/cookbook/user-authentication.md
  docs/en/security/authentication.md
Labels: enhancement

#457 Updates informatino about attributed rotes
  docs/en/http/annotated-routes.md
Labels: enhancement

#458 Updates informatino about serializer
  docs/en/component/serializer.md
  docs/en/cookbook/golang-library.md
  docs/en/manifest.json
  docs/en/readme.md
Labels: enhancement

#462 Move Custom HTTP request handler to the cookbook section
  docs/en/cookbook/psr-15.md
  docs/en/http/psr-15.md
  docs/en/manifest.json
  docs/en/readme.md
Labels: enhancement

#474 BUGFIX: define ViewsInterface in Twig Render Example
  docs/en/views/twig.md
Labels: section: VIEWS
