Repository spiral/docs, pull requests merged in 2023-02, with the labels that each got.

#487 Fix path for windows
  docs/en/start/installation.md
Labels: enhancement

#507 Updates icons
  docs/en/manifest.json
Labels: enhancement

#508 Fixes spiral/validator array checkers name
  docs/en/validation/spiral.md
Labels: bug, section: VALIDATION

#509 Improves information about queue component
  docs/en/basics/logging.md
  docs/en/queue/configuration.md
  docs/en/queue/jobs.md
  docs/en/queue/roadrunner.md
Labels: enhancement, section: QUEUE AND JOBS

#510 Fixes information about auth tokens for cycle orm
  docs/en/security/authentication.md
Labels: bug

#512 Adds sitemap for websocket services
  docs/en/websockets/services.md
Labels: enhancement

#513 Updates icons
  docs/en/manifest.json
Labels: bug

#515 Fixes small bugs
  docs/en/testing/database.md
Labels: bug
