Repository spiral/docs, pull requests merged in 2023-04, with the labels that each got.

#549 Removing http/golang - 3.4
  docs/en/grpc/service.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
Labels: bug

#548 Removing http/golang
  docs/en/grpc/service.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
Labels: bug

#547 Removing grpc/golang, grpc/streaming, http/golang - 3.2
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#546 Removing grpc/golang, grpc/streaming, http/golang - 3.1
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#544 Removing grpc/golang, grpc/streaming, http/golang - 3.0
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#543 Removing grpc/golang, grpc/streaming, http/golang - 2.14
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#542 Removing grpc/golang, grpc/streaming, http/golang - 2.13
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#541 Removing grpc/golang, grpc/streaming, http/golang - 2.12
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#540 Removing grpc/golang, grpc/streaming, http/golang - 2.11
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#539 Removing grpc/golang, grpc/streaming, http/golang - 2.10
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
  docs/en/readme.md
Labels: bug

#538 Removing http golang
  docs/en/http/golang.md
  docs/en/http/lifecycle.md
Labels: bug

#537 Remove grpc/golang and grpc/streaming
  docs/en/broadcast/publish.md
  docs/en/grpc/golang.md
  docs/en/grpc/service.md
  docs/en/grpc/streaming.md
  docs/en/readme.md
Labels: bug

#552 Removes RoadRunner config version
  docs/en/advanced/prometheus-metrics.md
  docs/en/basics/cache.md
  docs/en/cookbook/custom-dispatcher.md
  docs/en/grpc/configuration.md
  docs/en/queue/roadrunner.md
  docs/en/start/queue-basics.md
  docs/en/start/server.md
  docs/en/websockets/configuration.md
Labels: enhancement

#551 Removes RoadRunner config version
  docs/en/advanced/prometheus-metrics.md
  docs/en/basics/cache.md
  docs/en/cookbook/custom-dispatcher.md
  docs/en/grpc/configuration.md
  docs/en/queue/roadrunner.md
  docs/en/start/queue-basics.md
  docs/en/start/server.md
  docs/en/websockets/configuration.md
Labels: enhancement

#557 Updates scaffolder section
  docs/en/basics/scaffolding.md
Labels: enhancement, section: Scaffolder

#558 Updates information about roadrunner pipeline declaration and queue payload types
  docs/en/advanced/prometheus-metrics.md
  docs/en/basics/cache.md
  docs/en/basics/prototype.md
  docs/en/queue/jobs.md
  docs/en/queue/roadrunner.md
  docs/en/start/installation.md
  docs/en/start/server.md
Labels: enhancement, section: Cache, section: QUEUE AND JOBS

#559 Adds an example of Retry policy interceptor for failed jobs with explnation
  docs/en/queue/interceptors.md
Labels: section: QUEUE AND JOBS

#561 Adds information about available job handler invoke arguments
  docs/en/queue/jobs.md
Labels: section: QUEUE AND JOBS

#563 Adds information about caching tokenizer listeners
  docs/en/advanced/tokenizer.md
Labels: enhancement, section: Tokenizer

#565 Adds list of available env variables with description
  docs/en/start/configuration.md
Labels: enhancement, section: GETTING STARTED

#571 Adds information about exporters and env variables
  docs/en/advanced/telemetry.md
Labels: enhancement
